### ISSUE TITLE
Not Python 3.13 compatible

### ISSUE THREAD

**Issue by schniggie** [WebFuzzForge/wenum#95]
```
wenum
Traceback (most recent call last):
  File "/home/cd/hacktools/wenum/venv/bin/wenum", line 3, in <module>
    from wenum.main import main
  File "/home/cd/hacktools/wenum/src/wenum/__init__.py", line 51, in <module>
    from .runtime_session import FuzzSession
  File "/home/cd/hacktools/wenum/src/wenum/runtime_session.py", line 10, in <module>
    from .factories.fuzzresfactory import resfactory
  File "/home/cd/hacktools/wenum/src/wenum/factories/fuzzresfactory.py", line 3, in <module>
    from .fuzzfactory import reqfactory
  File "/home/cd/hacktools/wenum/src/wenum/factories/fuzzfactory.py", line 1, in <module>
    from ..fuzzrequest import FuzzRequest
  File "/home/cd/hacktools/wenum/src/wenum/fuzzrequest.py", line 4, in <module>
    from .externals.reqresp import Request, Response
  File "/home/cd/hacktools/wenum/src/wenum/externals/reqresp/__init__.py", line 1, in <module>
    from .Request import Request
  File "/home/cd/hacktools/wenum/src/wenum/externals/reqresp/Request.py", line 8, in <module>
    from .Response import Response
  File "/home/cd/hacktools/wenum/src/wenum/externals/reqresp/Response.py", line 2, in <module>
    import cgi
ModuleNotFoundError: No module named 'cgi'

```

See [https://docs.python.org/3/library/cgi.html](https://docs.python.org/3/library/cgi.html)

**Comment by Dontoronto** [comment]
Hello @schniggie, here are my steps to make wenum run under my kali arm64 version and python3.13. Hope this will help you

```bash
python3 -m pip install --user pipx
sudo apt-get install pyenv
pyenv install 3.11.9

# add this to ~/.bashrc
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - bash)"

pyenv shell 3.11.9
pipx install --python "$(pyenv which python3.11)" git+https://github.com/WebFuzzForge/wenum
pipx inject wenum setuptools
```

**Comment by KrazyyX** [comment]
@Dontoronto 's solution worked almost flawlessly for me. I just had to run:
```
pyenv init
``` 
and copy its output into ~/.zshrc instead.

**Comment by samoyed** [comment]
For an easier fix to not be reliant on pyenv, one can also use

`pipx runpip wenum install legacy-cgi`

wenum should work afterwards.

**Comment by 0xeygex** [comment]
@samoyed I love you man, I almost spend 3 hours to solve this issue

**Comment by Ahmedyahya12223** [comment]
hi @samoyed  do you have fix for this 

<img width="1116" height="356" alt="Image" src="https://github.com/user-attachments/assets/eea5435d-0ba1-4ea4-8c00-52ff5bf19cff" />

**Comment by hackinister** [comment]
hi @Ahmedyahya12223 i have a fix for this:

You can work around this by forcing an older setuptools version inside the wenum pipx venv (because pkg_resources was removed in setuptools>=82):

Install an older setuptools in the wenum venv:
```pipx runpip wenum uninstall setuptools
pipx runpip wenum install "setuptools<82"
# or explicitly:
pipx runpip wenum install "setuptools==81.0.0"```
